### PR TITLE
Naming rework

### PR DESCRIPTION
**Pull request by alexrsaff**
Old behaviour: Dockerfile names were derived from the following structure based on their location: "root/subfolder/Dockerfile.imageName".

New Behaviour: If the Dockerfile has an extension, then the name is derived as follows: "root/subfolder/Dockerfile.imageName". If the Docker file does not have an extension then the name is derived as follows: "root/imageName/Dockerfile".

### CODE REVIEW

**Comment by nafarlee** [comment]
I thought you had planned to drop the old `Docker.{{IMAGE_NAME}}` functionality?

**Comment by alexrsaff** [comment]
> 
> 
> I thought you had planned to drop the old `Docker.{{IMAGE_NAME}}` functionality?

oh I thought you wanted the new naming scheme as default behavior (without having to set any flags) with the old behavior as back up. I can remove the old behavior entirely if that's what you'd prefer.

**Comment by nafarlee** [comment]
> > I thought you had planned to drop the old `Docker.{{IMAGE_NAME}}` functionality?
> 
> oh I thought you wanted the new naming scheme as default behavior (without having to set any flags) with the old behavior as back up. I can remove the old behavior entirely if that's what you'd prefer.

Reasonable assumption, but as far as I know, no one makes extensive use of this action (yet). The old functionality, if not used by your team, will likely not be missed.

**Comment by alexrsaff** [comment]
> 
> 
> > > I thought you had planned to drop the old `Docker.{{IMAGE_NAME}}` functionality?
> > 
> > 
> > oh I thought you wanted the new naming scheme as default behavior (without having to set any flags) with the old behavior as back up. I can remove the old behavior entirely if that's what you'd prefer.
> 
> Reasonable assumption, but as far as I know, no one makes extensive use of this action (yet). The old functionality, if not used by your team, will likely not be missed.

Updated PR to remove the old naming scheme.

**Review by nafarlee — APPROVED** [review]

**Review by matttattoli — APPROVED** [review]

**Pull request merged**
